# -*- coding: utf-8 -*-
"""Salinan dari kalkulatorspldv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgVWWVhj_DwX2MeMe3KYCZsnP8yNz77v
"""

import streamlit as st

st.set_page_config(page_title="Kalkulator Jarak-Kecepatan-Waktu", page_icon="🛣️")

st.title("🛣️ Kalkulator Jarak - Kecepatan - Waktu")
st.write("Hitung salah satu dari tiga variabel fisika dasar: **Jarak**, **Kecepatan**, atau **Waktu**.")

# Pilihan perhitungan
pilihan = st.radio("Pilih yang ingin dihitung:", ["Jarak (km)", "Kecepatan (km/jam)", "Waktu (jam)"])

if pilihan == "Jarak (km)":
    kecepatan = st.number_input("Masukkan Kecepatan (km/jam):", min_value=0.0)
    waktu = st.number_input("Masukkan Waktu (jam):", min_value=0.0)
    if kecepatan and waktu:
        jarak = kecepatan * waktu
        st.success(f"🔹 Jarak = {jarak:.2f} km")

elif pilihan == "Kecepatan (km/jam)":
    jarak = st.number_input("Masukkan Jarak (km):", min_value=0.0)
    waktu = st.number_input("Masukkan Waktu (jam):", min_value=0.0)
    if waktu == 0 and jarak > 0:
        st.warning("Waktu tidak boleh nol!")
    elif jarak and waktu:
        kecepatan = jarak / waktu
        st.success(f"🔹 Kecepatan = {kecepatan:.2f} km/jam")

elif pilihan == "Waktu (jam)":
    jarak = st.number_input("Masukkan Jarak (km):", min_value=0.0)
    kecepatan = st.number_input("Masukkan Kecepatan (km/jam):", min_value=0.0)
    if kecepatan == 0 and jarak > 0:
        st.warning("Kecepatan tidak boleh nol!")
    elif jarak and kecepatan:
        waktu = jarak / kecepatan
        st.success(f"🔹 Waktu = {waktu:.2f} jam")